let leanData = {
    TW: {
        hd: {
            title: "遊戲機台說明"
        },
        menu: {
            list01: "柏青斯洛",
            list02: "15輪",
            list03: "EGT",
        },
        stepTitle: {
            step01: "機台介紹",
            step02: "機率概述",
            step03: "操作手冊",
            step04: "流程說明",
        },
        gizong: {
            step01: {
                main: "1 - 1. 機台介紹",
                title01: "廠商：",
                title02: "導入年月：",
                title03: "機種：",
                title04: "版本：",
                msg01: "點擊即可回到首頁。",
                msg02: "2003 / 07",
                msg03: "四號機 A Type",
                msg04: "爺verb. (爺面板)",
            },
            step02: {
                main01: "2 - 1. 開獎概述",
                main02: "2 - 2. 機率概述",
                title01: "基本 SPEC",
                title02: "通常時小役確率",
                title03: "內部 BONUS 抽選確率",
                tb01: {
                    th01: "小役",
                    th02: "銅鐘",
                    th03: "青再",
                    th04: "松",
                    th05: "紅櫻",
                    th06: "確率",
                },
                tb02: {
                    th01: "設定",
                    th02: "內部BIG",
                    th03: "內部REG",
                },
                tb03: {
                    th01: "設定",
                    th02: "內部REG",
                },
                tb04: {
                    th01: "獎勵倍數",
                    th02: "圖示",
                    Pieces: "枚",
                },
            },
            step03: {
                main01: "3 - 1. 畫面介紹",
                main02: "3 - 2. 按鈕介紹",
                main03: "3 - 3. 執行開分",
                main04: "3 - 4. 選擇模式",
                main05: "3 - 5. 機台錢包",
                main06: "3 - 6. 洗分換算",
                main07: "3 - 7. 保留遊戲",
                main08: "3 - 8. 結束遊戲",
                block01: {
                    title01: "錢包：",
                    title02: "大賞燈：",
                    title03: "機台錢包：",
                    title04: "得獎資訊：",
                    title05: "遊戲得分：",
                    msg01: "實際擁有及儲値點數顯示處。",
                    msg02: "大獎(BB)及小獎(RB)開獎紀錄、運轉次數。",
                    msg03: "機台本身點數也是主要遊戲扣點處; 最多 50枚。",
                    msg04: "開獎顯示處。",
                    msg05: "遊戲得分分數顯示。",
                },
                block02: {
                    relate01: "模式：自動 / 手動。",
                    relate02: "自動：機台自動RUN遊戲；如需停止，再點擊一下便可停止。",
                    relate03: "手動：手動點擊遊戲開始及暫停。",
                    title01: "保留：",
                    title02: "離開：",
                    title03: "重整：",
                    title04: "看表：",
                    title05: "履歷：",
                    title06: "開分：",
                    title07: "洗分：",
                    title08: "投幣：",
                    title09: "退幣：",
                    msg01: "遊戲機台做保留，其他人無法點選。",
                    msg02: "結束遊戲。",
                    msg03: "更新遊戲版面。",
                    msg04: "機台歷史紀錄。",
                    msg05: "當局遊戲紀錄(保留機台會延續累計；離開機台便重新統計)。",
                    msg06: "點數轉入進遊戲機台中，最低限制 100。",
                    msg07: "主錢包點數轉入錢包中，最低限制 100。",
                    msg08: "點選投幣按鈕便會從主錢包將點數轉入機台錢包。",
                    msg09: "機台錢包點數轉到主錢包上。",
                },
                block03: {
                    relate01: "進入遊戲後先執行開分，轉入點數送出後才可進行遊戲",
                    relate02: "每當進行遊戲時便會使用 3 枚代幣。當出現無滿足開分點數時，為遊戲機台本身已有存留代幣所導致。(以圖中情況來說，由於機台本身已留有2 枚代幣，故主錢包便會扣 1 枚，而顯示 49)。",
                    title01: "遊戲主錢包：",
                    title02: "機台錢包：",
                    msg01: "遊戲總分板。",
                    msg02: "機台本身點數也是主要遊戲扣點處; 最多 50枚開分 100主錢包及機台錢包分別會値入 50 。",
                },
                block04: {
                    relate01: "進入遊戲後選擇模式",
                    relate02: "執行遊戲可自動或手動方式執行",
                    title01: "手動模式",
                    title02: "自動模式",
                },
                block05: {
                    relate01: "投入金額換算遊戲錢包進行遊戲",
                    relate02: "當機台錢包為 0 時，點選投幣按鈕便會從主錢包將點數轉入機台錢包。",
                },
                block06: {
                    relate01: "點選洗分換算金額轉入自身錢包",
                    relate02: "再點選洗分按鈕，將主錢包點數轉至自己錢包中。",
                },
                block07: {
                    relate01: "需保留遊戲可點選左上角中的保留按鈕",
                    title01: "目的：",
                    msg01: "讓其他人無法點選。",
                },
                block08: {
                    relate01: "若要結束遊戲，只需點選左上角中的離開按鈕即可",
                    relate02: "如沒有選擇離開，系統將自動保留。",
                },
            },
            step04: {
                main: "4 - 1. 流程說明",
            },
        },
    },

    EN: {
        hd: {
            title: "Machine description"
        },
        menu: {
            list01: "SLOT",
            list02: "15Rounds",
            list03: "EGT",
        },
        stepTitle: {
            step01: "Introduction",
            step02: "Probability",
            step03: "Operating",
            step04: "Process",
        },
        gizong: {
            step01: {
                main: "1 - 1. Introduction",
                title01: "Vendor：",
                title02: "Import year and month：",
                title03: "Model：",
                title04: "Version：",
                msg01: "Click to return to the homepage.",
                msg02: "2003 / 07",
                msg03: "Four machine A Type.",
                msg04: "Grandpa verb.(grandpa panel)",
            },
            step02: {
                main01: "2 - 1. Draw Overview",
                main02: "2 - 2. Probability overview",
                title01: "Basic SPEC",
                title02: "Normal small role probability",
                title03: "Confirmation rate of internal BONUS lottery",
                tb01: {
                    th01: "Koi",
                    th02: "bell",
                    th03: "Qing Zai",
                    th04: "loose",
                    th05: "Red cherry",
                    th06: "probability",
                },
                tb02: {
                    th01: "set up",
                    th02: "Internal BIG",
                    th03: "Internal REG",
                },
                tb03: {
                    th01: "set up",
                    th02: "Internal REG",
                },
                tb04: {
                    th01: "Reward multiple",
                    th02: "Icon",
                    Pieces: "Sheets",
                },
            },
            step03: {
                main01: "3 - 1. Screen introduction",
                main02: "3 - 2. Button introduction",
                main03: "3 - 3. Perform opening points",
                main04: "3 - 4. Select mode",
                main05: "3 - 5. Machine Wallet",
                main06: "3 - 6. Washing points conversion",
                main07: "3 - 7. Keep the game",
                main08: "3 - 8. End the game",
                block01: {
                    title01: "wallet：",
                    title02: "Big reward light：",
                    title03: "Machine wallet：",
                    title04: "Winning Information：",
                    title05: "Game score：",
                    msg01: "Display of actual possession and stored value points.",
                    msg02: "Grand prize (BB) and small prize (RB) lottery records, number of runs.",
                    msg03: "The points of the machine itself are also the deduction points for the main game; up to 50 pieces.",
                    msg04: "The lottery display.",
                    msg05: "Game score points display.",
                },
                block02: {
                    relate01: "Mode：automatic / manual",
                    relate02: "Automatic：The machine automatically RUN the game; if you need to stop, click again to stop.",
                    relate03: "Manual：Manually click the game to start and pause.",
                    title01: "Keep：",
                    title02: "Go away：",
                    title03: "Reorganization：",
                    title04: "Look at the table：",
                    title05: "Resume：",
                    title06: "Opening points：",
                    title07: "Wash points：",
                    title08: "Coin：",
                    title09: "Withdrawal：",
                    msg01: "The game machine is reserved, and other people cannot click on it.",
                    msg02: "End Game.",
                    msg03: "Update the game layout.",
                    msg04: "Machine history.",
                    msg05: "The game record of the authorities (retaining the machine will continue to accumulate; leaving the machine will re-count).",
                    msg06: "The points are transferred into the game machine, and the minimum limit is 100.",
                    msg07: "The main wallet points are transferred to the wallet, and the minimum limit is 100.",
                    msg08: "Click the coin button to transfer the points from the main wallet to the machine wallet.",
                    msg09: "The machine wallet points are transferred to the main wallet.",
                },
                block03: {
                    relate01: "After entering the game, open the points first, and then the game can be played after the transfer points are sent.",
                    relate02: "tokens are used every time the game is played. When there is an unsatisfactory credit point, it is caused by the existing tokens in the gaming machine itself. (In the case of the picture, since the machine itself has 2 tokens, 1 token will be deducted from the main wallet, and 49 is displayed).",
                    title01: "Game main wallet：",
                    title02: "Machine wallet：",
                    msg01: "The game total score board.",
                    msg02: "The points of the machine itself are also the deduction points for the main game; the main wallet and machine wallet with up to 50 points will receive 50 points respectively.",
                },
                block04: {
                    relate01: "After entering the game, select the mode",
                    relate02: "The execution of the game can be executed automatically or manually",
                    title01: "Manual mode",
                    title02: "Auto mode",
                },
                block05: {
                    relate01: "Convert the amount invested into the game wallet to play the game.",
                    relate02: "When the machine wallet is 0, clicking the coin button will transfer the points from the main wallet to the machine wallet.",
                },
                block06: {
                    relate01: "Click to transfer the converted amount to your own wallet.",
                    relate02: "Then click the shuffle button to transfer the main wallet points to your own wallet.",
                },
                block07: {
                    relate01: "If you need to keep the game, click the keep button in the upper left corner.",
                    title01: "Purpose：",
                    msg01: "Make it impossible for others to click.",
                },
                block08: {
                    relate01: "To end the game, just click the leave button in the upper left corner",
                    relate02: "If you do not choose to leave, the system will automatically keep it.",
                },
            },
            step04: {
                main: "4 - 1. Process description",
            },
        },
    },
}